//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Resources.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RegExResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RegExResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Server.Resources.Resources.RegExResource", typeof(RegExResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^[\u0621-\u064A\u0660-\u0669 0-9  \\()@$&apos;/&amp;\0,._-]+$.
        /// </summary>
        public static string AuthorityNameArRegEx {
            get {
                return ResourceManager.GetString("AuthorityNameArRegEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^[a-z A-Z 0-9 \\\\()@$&apos;/&amp;\\0,._-]+$.
        /// </summary>
        public static string AuthorityNameEnRegEx {
            get {
                return ResourceManager.GetString("AuthorityNameEnRegEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^[\u0621-\u064A\u0660-\u0669 0-9  \\()@$&apos;/&amp;\0,._-]+$.
        /// </summary>
        public static string AwardNameArRegEx {
            get {
                return ResourceManager.GetString("AwardNameArRegEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^[a-z A-Z 0-9 \\\\()@$&apos;/&amp;\\0,._-]+$.
        /// </summary>
        public static string AwardNameEnRegEx {
            get {
                return ResourceManager.GetString("AwardNameEnRegEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^\w+([-+.&apos;]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$.
        /// </summary>
        public static string EmailRegEx {
            get {
                return ResourceManager.GetString("EmailRegEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?:(?:http|https):\/\/)?(?:www.)?facebook.com\/(?:(?:\w)*#!\/)?(?:pages\/)?(?:[?\w\-]*\/)?(?:profile.php\?id=(?=\d.*))?([\w\-]*)?.
        /// </summary>
        public static string FaceBookUrlRegEx {
            get {
                return ResourceManager.GetString("FaceBookUrlRegEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (https?)?:?(www?)?instagram\.com/[a-zA-Z0-9_].
        /// </summary>
        public static string InstagramUrlRegEx {
            get {
                return ResourceManager.GetString("InstagramUrlRegEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^https:\/\/[a-z]{2,3}\.linkedin\.com\/.*$.
        /// </summary>
        public static string LinkedInUrlRegEx {
            get {
                return ResourceManager.GetString("LinkedInUrlRegEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^(?:\+971|971|00971|0)?(?:50|51|52|53|54|55|56|58|2|3|4|6|7|9)\d{7}$.
        /// </summary>
        public static string MobileRegEx {
            get {
                return ResourceManager.GetString("MobileRegEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^[\u0621-\u064A\u0660-\u0669 \\]+$.
        /// </summary>
        public static string NameArRegEx {
            get {
                return ResourceManager.GetString("NameArRegEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^[a-z A-Z  \\\\()@$&apos;/&amp;\\0,._-]+$.
        /// </summary>
        public static string NameEnRegEx {
            get {
                return ResourceManager.GetString("NameEnRegEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[^\da-zA-Z]).{8,15}$.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (https?)?:?(www?)?twitter\.com/[a-zA-Z0-9_].
        /// </summary>
        public static string TwitterUrlRegEx {
            get {
                return ResourceManager.GetString("TwitterUrlRegEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 784\d{12}$.
        /// </summary>
        public static string UaeIdNumberRegEx {
            get {
                return ResourceManager.GetString("UaeIdNumberRegEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^[a-zA-Z][._a-zA-Z0-9]{5,11}.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^(https?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w \.-]*)*\/?$.
        /// </summary>
        public static string WebSiteRegEx {
            get {
                return ResourceManager.GetString("WebSiteRegEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^(http(s)?:\/\/)?((w){3}.)?youtu(be|.be)?(\.com)?\/.+.
        /// </summary>
        public static string YouTubeUrlRegEx {
            get {
                return ResourceManager.GetString("YouTubeUrlRegEx", resourceCulture);
            }
        }
    }
}
