// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System.Collections.Generic;

#nullable disable

namespace Server.Model.Models
{
    public partial class Brands
    {
        public Brands()
        {
            Products = new HashSet<Products>();
        }

        public int BrandId { get; set; }
        public string BrandNameAr { get; set; }
        public string BrandNameEn { get; set; }
        public bool? IsActive { get; set; }

        public virtual ICollection<Products> Products { get; set; }
    }
}