// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System.Collections.Generic;

#nullable disable

namespace Server.Model.Models
{
    public partial class Categories
    {
        public Categories()
        {
            Brands = new HashSet<Brands>();
            Products = new HashSet<Products>();
        }

        public int CategoryId { get; set; }
        public int? ParentCategoryId { get; set; }
        public string NameAr { get; set; }
        public string NameEn { get; set; }
        public bool? IsActive { get; set; }

        public virtual ICollection<Brands> Brands { get; set; }
        public virtual ICollection<Products> Products { get; set; }
    }
}