// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System.Collections.Generic;

#nullable disable

namespace Server.Model.Models
{
    public partial class Countries
    {
        public Countries()
        {
            Users = new HashSet<Users>();
        }

        public int CountryId { get; set; }
        public string Iso { get; set; }
        public string NameEn { get; set; }
        public string NameAr { get; set; }
        public string Iso3 { get; set; }
        public short? Code { get; set; }
        public int? PhoneCode { get; set; }
        public bool? IsActive { get; set; }

        public virtual ICollection<Users> Users { get; set; }
    }
}