// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Server.Model.Models
{
    public partial class ExceptionLogs
    {
        public int ExceptionId { get; set; }
        public DateTime ExceptionTime { get; set; }=DateTime.Now;
        public string ExceptionMessage { get; set; }
        public string ExceptionSource { get; set; }
        public string ExceptionStackTrack { get; set; }
        public string ExceptionDetails { get; set; }
        public string ControllerName { get; set; }
        public string ActionName { get; set; }
        public string RequestHeader { get; set; }
        public string RequestObject { get; set; }
        public string RequestMethodType { get; set; }
        public string RequestUrl { get; set; }
        public string ResponseObject { get; set; }
        public string ExceptionDescription { get; set; }
        public string DeviceName { get; set; }
        public string IpAddress { get; set; }
        public string HostName { get; set; }
    }
}