// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System.Collections.Generic;

#nullable disable

namespace Server.Model.Models
{
    public partial class OrderStates
    {
        public OrderStates()
        {
            OrderSteps = new HashSet<OrderSteps>();
            Orders = new HashSet<Orders>();
        }

        public int OrderStateId { get; set; }
        public string OrderState { get; set; }

        public virtual ICollection<OrderSteps> OrderSteps { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
    }
}