// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

#nullable disable

namespace Server.Model.Models
{
    public partial class OrderSteps
    {
        public int OrderStepId { get; set; }
        public int OrderId { get; set; }
        public int OrderStateId { get; set; }
        public DateTime? StateDate { get; set; }

        public virtual Orders Order { get; set; }
        public virtual OrderStates OrderState { get; set; }
    }
}