// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Server.Model.Models
{
    public partial class Products
    {
        public Products()
        {
            OrderDetails = new HashSet<OrderDetails>();
            ProductImages = new HashSet<ProductImages>();
            ProductTags = new HashSet<ProductTags>();
        }

        public int ProductId { get; set; }
        public string ProductKey { get; set; }
        public string ProductNameAr { get; set; }
        public string ProductNameEn { get; set; }
        public int CategoryId { get; set; }
        public int BrandId { get; set; }
        public int StockQuantiy { get; set; }
        public decimal Price { get; set; }
        public decimal Discount { get; set; }
        public DateTime CreatedDate { get; set; }
        public bool? IsActive { get; set; }

        public virtual Brands Brand { get; set; }
        public virtual Categories Category { get; set; }
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
        public virtual ICollection<ProductImages> ProductImages { get; set; }
        public virtual ICollection<ProductTags> ProductTags { get; set; }
    }
}