// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable disable

namespace Server.Model.Models
{
    public partial class ProductTags
    {
        public int ProductTagId { get; set; }
        public int ProductId { get; set; }
        public int TagId { get; set; }
        public bool? IsActive { get; set; }

        public virtual Products Product { get; set; }
        public virtual Tags Tag { get; set; }
    }
}