// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable disable

namespace Server.Model.Models
{
    public partial class ProductImages
    {
        public int ProductImageId { get; set; }
        public int ProductId { get; set; }
        public string ImageUrl { get; set; }
        public string ThumbnailImageUrl { get; set; }
        public bool? IsPrimary { get; set; }
        public bool? IsActive { get; set; }

        public virtual Products Product { get; set; }
    }
}