// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System.Collections.Generic;

#nullable disable

namespace Server.Model.Models
{
    public partial class Tags
    {
        public Tags()
        {
            ProductTags = new HashSet<ProductTags>();
        }

        public int TagId { get; set; }
        public string TagName { get; set; }
        public bool? IsActive { get; set; }

        public virtual ICollection<ProductTags> ProductTags { get; set; }
    }
}