// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System.Collections.Generic;

#nullable disable

namespace Server.Model.Models
{
    public partial class UserRoles
    {
        public UserRoles()
        {
            Users = new HashSet<Users>();
        }

        public int UserRoleId { get; set; }
        public string UserRole { get; set; }

        public virtual ICollection<Users> Users { get; set; }
    }
}